### ISSUE TITLE
Erros

### ISSUE THREAD

**Issue by brunorao** [claudiosanches/woocommerce-braspress#1]
Claudio, não sei oq ue pode estar errado. Mesmo com os valores preenchidos. recebo no log a mensagem:

An error has occurred. Message: CNPJ/CPF DO REMETENTE E/OU DESTINATARIO N¿O PODE(M) SER ZERO

Vimos que dá erro no cálcuo caso o CEP tenha o traço e também o CPF e CNPJ tenham pontos e traços, corrigimos.
Estamos usando junto o seu plugin dos checkout-fields e a versão do woocommerce 2.0.19.

Mesmo simulando uma compra com pessoa física com CPF e CNPJ validos prenchidos, retorna essa mensagem do campo vazio e o CNPJ do cliente braspress também está preenchido de acordo com somente números.

O que pode estar acontecendo? obrigado e somos fans seus pelos seus otimos plugins!

**Comment by claudiosanches** [comment]
Muito simples, eu não terminei este plugin aqui ainda xD

**Comment by claudiosanches** [comment]
Faltou uma conta de verdade no Braspress para testar e terminar o plugin.

**Comment by brunorao** [comment]
Entendi, quer que t passe uma? precisamos muito desse plugin, me confirma seu email que te envio. Pode ser?
