### ISSUE TITLE
Não está funcionando 

### ISSUE THREAD

**Issue by ojaneri** [claudiosanches/woocommerce-braspress#2]
Não esta funcionando, provavelmente devido a mudança no sistema da Braspress, que agora requer CPF do destinatário. 

Detalhe, entrando diretamente na página deles, e usando meu cpf como destinatário (ja sou cadastrado lá, pois ja recebi encomendas deles, a cotação dá certo, usando cpfs diferentes de pessoas que nunca receberam nada da braspress, dá esse erro também)

10-03-2014 @ 16:41:21 - Total order weight is 320000g and the total of items is 3
10-03-2014 @ 16:41:22 - An error has occurred. Message: CNPJ/CPF DO REMETENTE E/OU DESTINATARIO NÂ¿O PODE(M) SER ZERO
10-03-2014 @ 17:18:21 - Total order weight is 400000g and the total of items is 4
10-03-2014 @ 17:18:22 - An error has occurred. Message: CNPJ/CPF DO REMETENTE E/OU DESTINATARIO NÂ¿O PODE(M) SER ZERO

Talvez colocar CPF destinatário nas configurações e passar essa opção para o webservice da braspress?

Obrigado!

**Comment by claudiosanches** [comment]
Então esta tudo certo, não era para funcionar mesmo, porque o plugin nunca foi terminado.

**Comment by ojaneri** [comment]
Mexendo nele passei para ´outro´ level, e apareceu
10-03-2014 @ 17:48:30 - Total order weight is 80000g and the total of items
is 1
10-03-2014 @ 17:48:31 - An error has occurred. Message: CARREGANDO ALIQUOTA
DE PIS E COFINS

Sera que não é possivel coloca-lo pra funcionar? Entendo que o Claudio deve
ter abandonado o projeto por estar sobrecarregado, mas alguém deve estar
precisando também. :) Alguem mais pode tentar ajudar? Vou continuar olhando e ve se consigo algo.

2014-10-03 14:27 GMT-03:00 Claudio Sanches notifications@github.com:

**Comment by claudiosanches** [comment]
Não, larguei o projeto por não conseguir nenhum apoio da Braspress e testando com 5 pessoas ninguém conseguia ativar a API.

**Comment by ojaneri** [comment]
Posso tentar ajudar? A empresa que trabalho tem cadastro na Braspress ativo e tenho alguns contatos por lá.

Por exemplo, mudando agora e colocando meu CPF, apontou esse erro que passei acima. 

$request->setDocumentoDestino( 'MEUCPF' );

Acho que agora eles estão amarrando tudo e tanto remet como dest tem que estarem cadastrados.

**Comment by claudiosanches** [comment]
Se precisam estar cadastrados não vai funcionar muito bem para o cotar o valor.

Em todos os meus testes sempre a API retorna:

```
10-03-2014 @ 17:48:31 - An error has occurred. Message: CARREGANDO ALIQUOTA
DE PIS E COFINS
```

E nunca passei dai.
