### ISSUE TITLE
ID Braspress

### ISSUE THREAD

**Issue by bubag3** [claudiosanches/woocommerce-braspress#3]
Entrei em contato com a Braspress para fornecerem esse ID, porém nem eles mesmos sabem do que se trata. O que seria esse ID?

**Comment by claudiosanches** [comment]
Boa pergunta, estava na API deles, mas este plugin não funciona, exatamente porque a API deles não funciona.
Boa sorte com isso ;)

**Comment by claudiosanches** [comment]
Recomendo ler o aviso que deixei:

> WooCommerce Braspress - Este plugin esta em desenvolvimento e provavelmente nunca será terminado, simplesmente porque eu não consigo acesso a API da Braspress e ninguém consegue isso para me ajudar =/
