### ISSUE TITLE
Que acesso precisa?

### ISSUE THREAD

**Issue by bergpinheiro** [claudiosanches/woocommerce-braspress#4]
Que acesso precisa amigo?

**Comment by claudiosanches** [comment]
Acesso a documentação oficial e qualquer chave de API ou o que precisar para poder usar.

**Comment by bergpinheiro** [comment]
Vou entrar em contato com eles. Sou cliente deles.
Aproveitando gostaria de saber se tem interesse de fazer um para a transportadora jadlog. Deles tenho login e senha do web-service .

**Comment by claudiosanches** [comment]
Se conseguir documentação e acesso da API do Jadlog eu consigo tentar fazer plugin.

**Comment by bergpinheiro** [comment]
Ja tenho acesso api e a documentação da jadlog. Por onde posso enviar?

**Comment by bergpinheiro** [comment]
@claudiosanches Segue a documentação. A senha de acesso ao web service te envio por e-mail. Aguardo o e-mail
[web-service-jad-log.PDF](https://github.com/claudiosanches/woocommerce-braspress/files/1352294/web-service-jad-log.PDF)

**Comment by brunoborges92** [comment]
@claudiosanches Tudo bem? você chegou a fazer o plugin? se precisar do login de acesso ao web service eu tenho.

**Comment by claudiosanches** [comment]
@brunoborges92 tem mesmo acesso e documentação?

**Comment by brunoborges92** [comment]
@claudiosanches tenho sim.  
Documentação esta aqui, me passa seu e-mail para eu enviar as informações de acesso.
[Documentação Web Service JadLog_7_0.pdf](https://github.com/claudiosanches/woocommerce-braspress/files/1838435/Documentacao.Web.Service.JadLog_7_0.pdf)

**Comment by claudiosanches** [comment]
@brunoborges92 a Braspress virou Jadlog agora?

**Comment by claudiosanches** [comment]
@brunoborges92 a Braspress virou Jadlog agora?

**Comment by brunoborges92** [comment]
@claudiosanches  acredito que não.
Eu vi que não coloquei a transportadora na minha primeira pergunta.
Mas eu estava falando sobre um comentário que você tinha feito.

"Se conseguir documentação e acesso da API do Jadlog eu consigo tentar fazer plugin."

**Comment by claudiosanches** [comment]
Tópico é do Braspress e tem plugin já da Jadlog pronto.
